#!/usr/bin/env python
# Installs the dotfiles via symlinks

import os
import sys
import subprocess

file_list = ['vimrc', 'gvimrc', 'vim', 'gitignore']

if __name__ == '__main__':
    for file_name in file_list:
        command_list = ['ln']
        args_string = list('-')
        if 'darwin' in sys.platform or 'bsd' in sys.platform:
            if os.path.isdir(file_name): args_string.append('Fh')
        if os.path.exists(file_name): args_string.append('f')
        args_string.append('sv')
        command_list.append(''.join(args_string))
        command_list.append('{0}/{1}'.format(os.getcwd(), file_name))
        command_list.append(os.path.expanduser('~/.{0}'.format(file_name)))
        subprocess.call(command_list)
