# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 3
console_title_template: "{{.PWD}} on {{ lower .HostName }}"
shell_integration: true
auto_upgrade: true
final_space: true
# based on gruvbox dark palette
palette:
  bg:0: "#1d2021"
  bg:1: "#3c3836"
  bg:2: "#504945"
  bg:3: "#665c54"
  bg:4: "#7c6f64"
  bg:aqua: "#689d6a"
  bg:blue: "#458588"
  bg:gray: "#928374"
  bg:green: "#98971a"
  bg:main: "#282828"
  bg:orange: "#d65d0e"
  bg:purple: "#b16286"
  bg:red: "#cc241d"
  bg:yellow: "#d79921"
  fg:0: "#fbf1c7"
  fg:1: "#ebdbb2"
  fg:2: "#d5c4a1"
  fg:3: "#bdae93"
  fg:4: "#a89984"
  fg:aqua: "#8ec07c"
  fg:blue: "#83a598"
  fg:green: "#b8bb26"
  fg:main: "#ebdbb2"
  fg:orange: "#fe8019"
  fg:purple: "#d3869b"
  fg:red: "#fb4934"
  fg:yellow: "#fabd2f"
blocks:
  - alignment: left
    type: prompt
    segments:
      - background: p:bg:yellow
        foreground: p:bg:main
        properties:
          display_host: false
        style: diamond
        template: >-
          {{if .SSHSession }} 󰌘{{end}}
          {{lower .UserName}}󰁥{{lower .HostName}} 
        trailing_diamond: 
        type: session
      - background: p:bg:orange
        foreground: p:bg:main
        leading_diamond: <transparent,background></>
        properties:
          folder_icon: 
          folder_separator_icon: "  "
          home_icon: 
          style: mixed
        style: diamond
        template: " {{ path .Path .Location }} "
        trailing_diamond: 
        type: path
      - background: p:bg:green
        background_templates:
          - "{{if or (.Working.Changed) (.Staging.Changed)}}p:bg:yellow{{end}}"
          - "{{if and (gt .Ahead 0) (gt .Behind 0)}}p:bg:red{{end}}"
          - "{{if gt .Ahead 0}}p:bg:purple{{end}}"
          - "{{if gt .Behind 0}}p:bg:aqua{{end}}"
        foreground: p:bg:main
        foreground_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed)}}p:bg:main{{end}}"
          - "{{if and (gt .Ahead 0) (gt .Behind 0)}}p:fg:main{{end}}"
          - "{{if gt .Ahead 0}}p:fg:main{{end}}"
        leading_diamond: <transparent,background></>
        properties:
          fetch_status: true
          fetch_upstream_icon: true
          github_icon: 
        style: diamond
        template: >-
          {{ if .UpstreamURL}} {{url .UpstreamIcon .UpstreamURL }}{{ end }}
          {{ .HEAD }}
          {{ if .BranchStatus }}{{ .BranchStatus }}{{ end -}}
          {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}
          {{ if and (.Working.Changed) (.Staging.Changed) }}󰇙{{ end }}
          {{ if .Staging.Changed -}}  {{ .Staging.String }}{{ end }}
          {{ if gt .StashCount 0 }} 󰧯 {{ .StashCount }}{{ end }}
        trailing_diamond: 
        type: git
      - background: p:bg:purple
        foreground: p:bg:white
        leading_diamond: <transparent,background></>
        properties:
          root_icon: 
        style: diamond
        template: 
        trailing_diamond: 
        type: root
      - background: p:bg:blue
        background_templates:
          - "{{if ne .Code 0}}p:bg:red{{end}}"
        foreground: p:fg:main
        leading_diamond: <transparent,background></>
        properties:
          always_enabled: true
        style: diamond
        template: " {{if eq .Code 0}}{{else}} {{ reason .Code }}{{end}} "
        trailing_diamond: 
        type: status
