return {
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "html",
    "ini",
    "javascript",
    "jsdoc",
    "json",
    "jsonc",
    "lua",
    "markdown",
    "markdown_inline",
    "ninja",
    "proto",
    "python",
    "query",
    "rust",
    "toml",
    "typescript",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zig",
  },
  highlight = {
    additional_vim_regex_highlighting = { "dockerfile", "cmake", "make" },
    enable = true,
    disable = { "dockerfile" },
  },
  incremental_selection = { enable = true },
  indent = { enable = true, disable = { "lua" } },
}
